version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: proffy
      POSTGRES_PASSWORD: proffy
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432

  # You can open adminer at localhost:8080. It's like a database manager
  adminer:
    image: adminer
    container_name: adm
    restart: always
    ports:
      - 8080:8080
